
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 12566
 */
public class movieGui extends javax.swing.JFrame {

    public static boolean RETRIEVEMOVIELIST = true;
    public static boolean RETRIEVEMOVIETIMES = true;
    public static String movie = "test";
    
    /**
     * Creates new form movieGui
     */
    public movieGui() {
        initComponents();
        currentMoviesTxt.setVisible(false);
        movieList.setVisible(false);        
        findShowtimesButton.setVisible(false);
        currentTimesTxt.setVisible(false);
        timesList.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        jPanel1 = new javax.swing.JPanel();
        movieHeaderTxt = new javax.swing.JTextField();
        currentMoviesTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieList = new java.awt.List();
        findShowtimesButton = new javax.swing.JButton();
        currentTimesTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        timesList = new java.awt.List();
        retriveMoviesButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        movieHeaderTxt.setEditable(false);
        movieHeaderTxt.setText("Movie Times for Madison Square 12");
       

        currentMoviesTxt.setEditable(false);
        currentMoviesTxt.setText("Current Movies");
      

        movieList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieListActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(movieList);

        findShowtimesButton.setText("Find Showtimes");
        findShowtimesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findShowtimesButtonActionPerformed(evt);
            }
        });

        currentTimesTxt.setEditable(false);
        currentTimesTxt.setText("Times");
        
        jScrollPane2.setViewportView(timesList);

        retriveMoviesButton.setText("Retrieve Shown Movies");
        retriveMoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retriveMoviesButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movieHeaderTxt)
                    .addComponent(retriveMoviesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(findShowtimesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 133, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(currentMoviesTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentTimesTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(movieHeaderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retriveMoviesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentMoviesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentTimesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findShowtimesButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton))
        );

        pack();
    }// </editor-fold>  


    //SERVER ACTION
    private void retriveMoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retriveMoviesButtonActionPerformed
        RETRIEVEMOVIELIST = true;
        retriveMoviesButton.setVisible(false);
        currentMoviesTxt.setVisible(true);
        movieList.setVisible(true);
        
        //get string Array from the server
        String[] importedMovieList = Client.movieTitles;
        
        int itemsInList=importedMovieList.length;
        
        //Populate the Movie list with the string array from the server
        for(int temp=0; temp <itemsInList; temp++){
        movieList.add(importedMovieList[temp]);
        };
        RETRIEVEMOVIELIST = false;
            }//GEN-LAST:event_retriveMoviesButtonActionPerformed

  
    private void movieListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieListActionPerformed

        findShowtimesButton.setVisible(true);
    }//GEN-LAST:event_movieListActionPerformed
   

//SERVER ACTION
    private void findShowtimesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findShowtimesButtonActionPerformed
        //remove any items in TimesList
        timesList.removeAll();
        
        RETRIEVEMOVIETIMES = true;
        movie = movieList.getSelectedItem();
        //Send movie to Server
        // pause to allow communication to server to finish
        
        //get string Array from the server    
        String[] importedTimeList = Client.getMovieTimes(movie);
        
       
        
        
        //Fill Times list with movies from Server
        int itemsInList=importedTimeList.length;
        
        for(int temp=0; temp <itemsInList; temp++){
        timesList.add(importedTimeList[temp]);
        };
        
        findShowtimesButton.setVisible(false);
        
        currentTimesTxt.setVisible(true);
        timesList.setVisible(true);
        RETRIEVEMOVIETIMES = false;  
        
    }//GEN-LAST:event_findShowtimesButtonActionPerformed

    
    //EXIT BUTTON
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.exit(0);
    }  
    
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currentMoviesTxt;
    private javax.swing.JTextField currentTimesTxt;
    private javax.swing.JButton findShowtimesButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField movieHeaderTxt;
    private java.awt.List movieList;
    private javax.swing.JButton retriveMoviesButton;
    private java.awt.List timesList;
    private javax.swing.JButton exitButton;
    // End of variables declaration//GEN-END:variables

}
